language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - REQ="Django>=1.7,<1.8"
  - REQ="Django>=1.8,<1.9"
  - REQ="Django>=1.9,<1.10"
  - REQ="Django>=1.10,<1.11"
  - REQ="Django>=1.11,<2.0"
  - REQ="https://github.com/django/django/archive/master.zip"
matrix:
  exclude:
    - python: "2.7"
      env: REQ="https://github.com/django/django/archive/master.zip"
    - python: "3.5"
      env: REQ="Django>=1.7,<1.8"
      # Django 1.7 does not support Python 3.5
  allow_failures:
    - env: REQ="https://github.com/django/django/archive/master.zip"
install:
  - pip install $REQ coverage pytz
  - python setup.py install
script: "cd tests && ./manage.py test testapp"
